# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_remove_info_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpu', models.CharField(max_length=40)),
                ('Precpu', models.CharField(max_length=40)),
            ],
        ),
    ]
