# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_remove_cpu_mem_precpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_mem',
            name='Ip',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AddField(
            model_name='cpu_mem',
            name='Time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='Command',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='Port',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
