# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20171113_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_mem',
            name='Number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
