# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_cpu_mem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_mem',
            name='Time_float',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
