# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_cpu_mem_time_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu_mem',
            old_name='Number',
            new_name='Cid',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='number',
            new_name='Cid',
        ),
    ]
