# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_auto_20171122_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
