# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0011_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Port',
            new_name='PrivatePort',
        ),
        migrations.AddField(
            model_name='info',
            name='PublicPort',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='info',
            name='Type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
