# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0012_auto_20171204_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_mem',
            name='Rx',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AddField(
            model_name='cpu_mem',
            name='Tx',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
