# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Architecture', models.CharField(max_length=20)),
                ('ServerVersion', models.CharField(max_length=20)),
                ('NCPU', models.CharField(max_length=20)),
                ('MemTotal', models.CharField(max_length=20)),
                ('Containers', models.CharField(max_length=20)),
                ('ContainersPaused', models.CharField(max_length=20)),
                ('ContainersRunning', models.CharField(max_length=20)),
                ('ContainersStopped', models.CharField(max_length=20)),
                ('Images', models.CharField(max_length=20)),
            ],
        ),
    ]
