# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Name',
            field=models.CharField(max_length=28),
        ),
    ]
