# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171023_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='Ip',
            field=models.CharField(max_length=33),
        ),
    ]
