# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171023_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Ip',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
