# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_info_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='OperatingSystem',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
