# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_info_operatingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='Tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
