# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ip_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Tag',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
